// <auto-generated />
using System;
using KStyleDiary.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KStyleDiary.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251225170334_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("KStyleDiary.Models.Look", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatingDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Mood")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Looks");
                });

            modelBuilder.Entity("KStyleDiary.Models.LookProduct", b =>
                {
                    b.Property<int>("LookId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UsageNote")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("LookId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("LookProducts");
                });

            modelBuilder.Entity("KStyleDiary.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Brand")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("KStyleDiary.Models.LookProduct", b =>
                {
                    b.HasOne("KStyleDiary.Models.Look", "Look")
                        .WithMany("LookProducts")
                        .HasForeignKey("LookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KStyleDiary.Models.Product", "Product")
                        .WithMany("LookProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Look");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("KStyleDiary.Models.Look", b =>
                {
                    b.Navigation("LookProducts");
                });

            modelBuilder.Entity("KStyleDiary.Models.Product", b =>
                {
                    b.Navigation("LookProducts");
                });
#pragma warning restore 612, 618
        }
    }
}
